//
//  AtomGeID.m
//  MPEG4FileViewer
//
//  Created by Jay O'Conor on 3/17/14.
//  Copyright (c) 2014 Jay O'Conor. All rights reserved.
//

#import "AtomGeID.h"

@implementation AtomGeID

static dispatch_once_t pred;
static NSDictionary *genreDict;

+(void)load
{
    [self populateAtomToClassDict];
}

+(NSString *)atomType
{
    return (@"geID");
}

- (NSString *)atomName
{
    return NSLocalizedStringFromTable(@"Genre ID",
                                      @"atomName",
                                      @"Atom geID name");
}

- (NSString *)html
{
    NSString *genreID;

    dispatch_once (&pred, ^{
        genreDict = @{
                      // Genre ID list from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html
                      // Music
                      @2 : NSLocalizedStringFromTable(@"Blues",
                                                      @"geID-Music",
                                                      @"Genre 2 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @3 : NSLocalizedStringFromTable(@"Comedy",
                                                      @"geID-Music",
                                                      @"Genre 3 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4 : NSLocalizedStringFromTable(@"Children’s Music",
                                                      @"geID-Music",
                                                      @"Genre 4 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @5 : NSLocalizedStringFromTable(@"Classical",
                                                      @"geID-Music",
                                                      @"Genre 5 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @6 : NSLocalizedStringFromTable(@"Country",
                                                      @"geID-Music",
                                                      @"Genre 6 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @7 : NSLocalizedStringFromTable(@"Electronic",
                                                      @"geID-Music",
                                                      @"Genre 7 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @8 : NSLocalizedStringFromTable(@"Holiday",
                                                      @"geID-Music",
                                                      @"Genre 8 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @9 : NSLocalizedStringFromTable(@"Opera",
                                                      @"geID-Music",
                                                      @"Genre 9 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @10 : NSLocalizedStringFromTable(@"Singer/Songwriter",
                                                       @"geID-Music",
                                                       @"Genre 10 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @11 : NSLocalizedStringFromTable(@"Jazz",
                                                       @"geID-Music",
                                                       @"Genre 11 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @12 : NSLocalizedStringFromTable(@"Latino",
                                                       @"geID-Music",
                                                       @"Genre 12 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @13 : NSLocalizedStringFromTable(@"New Age",
                                                       @"geID-Music",
                                                       @"Genre 13 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @14 : NSLocalizedStringFromTable(@"Pop",
                                                       @"geID-Music",
                                                       @"Genre 14 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @15 : NSLocalizedStringFromTable(@"R&B/Soul",
                                                       @"geID-Music",
                                                       @"Genre 15 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @16 : NSLocalizedStringFromTable(@"Soundtrack",
                                                       @"geID-Music",
                                                       @"Genre 16 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @17 : NSLocalizedStringFromTable(@"Dance",
                                                       @"geID-Music",
                                                       @"Genre 17 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @18 : NSLocalizedStringFromTable(@"Hip-Hop/Rap",
                                                       @"geID-Music",
                                                       @"Genre 18 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @19 : NSLocalizedStringFromTable(@"World",
                                                       @"geID-Music",
                                                       @"Genre 19 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @20 : NSLocalizedStringFromTable(@"Alternative",
                                                       @"geID-Music",
                                                       @"Genre 20 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @21 : NSLocalizedStringFromTable(@"Rock",
                                                       @"geID-Music",
                                                       @"Genre 21 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @22 : NSLocalizedStringFromTable(@"Christian & Gospel",
                                                       @"geID-Music",
                                                       @"Genre 22 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @23 : NSLocalizedStringFromTable(@"Vocal",
                                                       @"geID-Music",
                                                       @"Genre 23 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @24 : NSLocalizedStringFromTable(@"Reggae",
                                                       @"geID-Music",
                                                       @"Genre 24 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @25 : NSLocalizedStringFromTable(@"Easy Listening",
                                                       @"geID-Music",
                                                       @"Genre 25 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @27 : NSLocalizedStringFromTable(@"J-Pop",
                                                       @"geID-Music",
                                                       @"Genre 27 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @28 : NSLocalizedStringFromTable(@"Enka",
                                                       @"geID-Music",
                                                       @"Genre 28 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @29 : NSLocalizedStringFromTable(@"Anime",
                                                       @"geID-Music",
                                                       @"Genre 29 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @30 : NSLocalizedStringFromTable(@"Kayokyoku",
                                                       @"geID-Music",
                                                       @"Genre 30 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @50 : NSLocalizedStringFromTable(@"Fitness & Workout",
                                                       @"geID-Music",
                                                       @"Genre 50 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @51 : NSLocalizedStringFromTable(@"K-Pop",
                                                       @"geID-Music",
                                                       @"Genre 51 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @52 : NSLocalizedStringFromTable(@"Karaoke",
                                                       @"geID-Music",
                                                       @"Genre 52 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @53 : NSLocalizedStringFromTable(@"Instrumental",
                                                       @"geID-Music",
                                                       @"Genre 53 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1122 : NSLocalizedStringFromTable(@"Brazilian",
                                                         @"geID-Music",
                                                         @"Genre 1122 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      // Music Videos
                      @1602 : NSLocalizedStringFromTable(@"Blues",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1602 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1603 : NSLocalizedStringFromTable(@"Comedy",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1603 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1604 : NSLocalizedStringFromTable(@"Children’s Music",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1604 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1605 : NSLocalizedStringFromTable(@"Classical",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1605 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1606 : NSLocalizedStringFromTable(@"Country",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1606 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1607 : NSLocalizedStringFromTable(@"Electronic",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1607 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1608 : NSLocalizedStringFromTable(@"Holiday",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1608 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1609 : NSLocalizedStringFromTable(@"Opera",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1609 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1610 : NSLocalizedStringFromTable(@"Singer/Songwriter",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1610 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1611 : NSLocalizedStringFromTable(@"Jazz",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1611 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1612 : NSLocalizedStringFromTable(@"Latino",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1612 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1613 : NSLocalizedStringFromTable(@"New Age",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1613 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1614 : NSLocalizedStringFromTable(@"Pop",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1614 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1615 : NSLocalizedStringFromTable(@"R&B/Soul",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1615 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1616 : NSLocalizedStringFromTable(@"Soundtrack",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1616 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1617 : NSLocalizedStringFromTable(@"Dance",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1617 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1618 : NSLocalizedStringFromTable(@"Hip-Hop/Rap",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1618 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1619 : NSLocalizedStringFromTable(@"World",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1619 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1620 : NSLocalizedStringFromTable(@"Alternative",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1620 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1621 : NSLocalizedStringFromTable(@"Rock",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1621 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1622 : NSLocalizedStringFromTable(@"Christian & Gospel",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1622 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1623 : NSLocalizedStringFromTable(@"Vocal",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1623 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1624 : NSLocalizedStringFromTable(@"Reggae",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1624 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1625 : NSLocalizedStringFromTable(@"Easy Listening",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1625 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1626 : NSLocalizedStringFromTable(@"Podcasts",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1626 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1627 : NSLocalizedStringFromTable(@"J-Pop",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1627 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1628 : NSLocalizedStringFromTable(@"Enka",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1628 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1629 : NSLocalizedStringFromTable(@"Anime",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1629 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1630 : NSLocalizedStringFromTable(@"Kayokyoku",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1630 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1631 : NSLocalizedStringFromTable(@"Disney",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1631 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1632 : NSLocalizedStringFromTable(@"French Pop",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1632 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1633 : NSLocalizedStringFromTable(@"German Pop",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1633 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @1634 : NSLocalizedStringFromTable(@"German Folk",
                                                         @"geID-MusicVideos",
                                                         @"Genre 1634 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      // TV Shows
                      @4000 : NSLocalizedStringFromTable(@"Comedy",
                                                         @"geID-TVShows",
                                                         @"Genre 4000 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4001 : NSLocalizedStringFromTable(@"Drama",
                                                         @"geID-TVShows",
                                                         @"Genre 4001 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4002 : NSLocalizedStringFromTable(@"Animation",
                                                         @"geID-TVShows",
                                                         @"Genre 4002 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4003 : NSLocalizedStringFromTable(@"Action & Adventure",
                                                         @"geID-TVShows",
                                                         @"Genre 4003 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4004 : NSLocalizedStringFromTable(@"Classic",
                                                         @"geID-TVShows",
                                                         @"Genre 4004 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4005 : NSLocalizedStringFromTable(@"K4005s",
                                                         @"geID-TVShows",
                                                         @"Genre 4005 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4006 : NSLocalizedStringFromTable(@"Nonfiction",
                                                         @"geID-TVShows",
                                                         @"Genre 4006 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4007 : NSLocalizedStringFromTable(@"Reality TV",
                                                         @"geID-TVShows",
                                                         @"Genre 4007 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4008 : NSLocalizedStringFromTable(@"Sci-Fi & Fantasy",
                                                         @"geID-TVShows",
                                                         @"Genre 4008 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4009 : NSLocalizedStringFromTable(@"Sports",
                                                         @"geID-TVShows",
                                                         @"Genre 4009 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4010 : NSLocalizedStringFromTable(@"Teens",
                                                         @"geID-TVShows",
                                                         @"Genre 4010 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4011 : NSLocalizedStringFromTable(@"Latino TV",
                                                         @"geID-TVShows",
                                                         @"Genre 4011 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      // Movies
                      @4401 : NSLocalizedStringFromTable(@"Action & Adventure",
                                                         @"geID-Movies",
                                                         @"Genre 4401 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4402 : NSLocalizedStringFromTable(@"Anime",
                                                         @"geID-Movies",
                                                         @"Genre 4402 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4403 : NSLocalizedStringFromTable(@"Classics",
                                                         @"geID-Movies",
                                                         @"Genre 4403 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4404 : NSLocalizedStringFromTable(@"Comedy",
                                                         @"geID-Movies",
                                                         @"Genre 4404 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4405 : NSLocalizedStringFromTable(@"Documentary",
                                                         @"geID-Movies",
                                                         @"Genre 4405 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4406 : NSLocalizedStringFromTable(@"Drama",
                                                         @"geID-Movies",
                                                         @"Genre 4406 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4407 : NSLocalizedStringFromTable(@"Foreign",
                                                         @"geID-Movies",
                                                         @"Genre 4407 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4408 : NSLocalizedStringFromTable(@"Horror",
                                                         @"geID-Movies",
                                                         @"Genre 4408 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4409 : NSLocalizedStringFromTable(@"Independent",
                                                         @"geID-Movies",
                                                         @"Genre 4409 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4410 : NSLocalizedStringFromTable(@"Kids & Family",
                                                         @"geID-Movies",
                                                         @"Genre 4410 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4411 : NSLocalizedStringFromTable(@"Musicals",
                                                         @"geID-Movies",
                                                         @"Genre 4411 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4412 : NSLocalizedStringFromTable(@"Romance",
                                                         @"geID-Movies",
                                                         @"Genre 4412 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4413 : NSLocalizedStringFromTable(@"Sci-Fi & Fantasy",
                                                         @"geID-Movies",
                                                         @"Genre 4412 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4414 : NSLocalizedStringFromTable(@"Short Films",
                                                         @"geID-Movies",
                                                         @"Genre 4414 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4415 : NSLocalizedStringFromTable(@"Special Interest",
                                                         @"geID-Movies",
                                                         @"Genre 4415 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4416 : NSLocalizedStringFromTable(@"Thriller",
                                                         @"geID-Movies",
                                                         @"Genre 4416 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4417 : NSLocalizedStringFromTable(@"Sports",
                                                         @"geID-Movies",
                                                         @"Genre 4417 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4418 : NSLocalizedStringFromTable(@"Western",
                                                         @"geID-Movies",
                                                         @"Genre 4418 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4419 : NSLocalizedStringFromTable(@"Urban",
                                                         @"geID-Movies",
                                                         @"Genre 4419 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4420 : NSLocalizedStringFromTable(@"Holiday",
                                                         @"geID-Movies",
                                                         @"Genre 4420 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4421 : NSLocalizedStringFromTable(@"Made for TV",
                                                         @"geID-Movies",
                                                         @"Genre 4421 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4422 : NSLocalizedStringFromTable(@"Concert Films",
                                                         @"geID-Movies",
                                                         @"Genre 4422 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4423 : NSLocalizedStringFromTable(@"Music Documentaries",
                                                         @"geID-Movies",
                                                         @"Genre 4423 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4424 : NSLocalizedStringFromTable(@"Music Feature Films",
                                                         @"geID-Movies",
                                                         @"Genre 4424 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4425 : NSLocalizedStringFromTable(@"Japanese Cinema",
                                                         @"geID-Movies",
                                                         @"Genre 4425 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4426 : NSLocalizedStringFromTable(@"Jidaigeki",
                                                         @"geID-Movies",
                                                         @"Genre 4426 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4427 : NSLocalizedStringFromTable(@"Tokusatsu",
                                                         @"geID-Movies",
                                                         @"Genre 4427 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @4428 : NSLocalizedStringFromTable(@"Korean Cinema",
                                                         @"geID-Movies",
                                                         @"Genre 4428 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      // Music
                      @50000061 : NSLocalizedStringFromTable(@"Spoken Word",
                                                             @"geID-Music",
                                                             @"Genre 50000061 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @50000063 : NSLocalizedStringFromTable(@"Disney",
                                                             @"geID-Music",
                                                             @"Genre 50000063 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @50000064 : NSLocalizedStringFromTable(@"French Pop",
                                                             @"geID-Music",
                                                             @"Genre 50000064 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @50000066 : NSLocalizedStringFromTable(@"German Pop",
                                                             @"geID-Music",
                                                             @"Genre 50000066 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html"),
                      @50000068 : NSLocalizedStringFromTable(@"German Folk",
                                                             @"geID-Music",
                                                             @"Genre 50000068 from http://www.apple.com/itunes/affiliates/resources/documentation/genre-mapping.html")
                      };
    });
    genreID = genreDict[@([self asInteger])];
    if (!genreID) {
        genreID = NSLocalizedString(@"Unknown Genre ID",
                                    @"String to use when Genre ID (geID) not found");
    }
    NSString *html = [NSString stringWithFormat:@"<body><span style=\"font-size: 14px\"><font face=\"AvenirNext-Medium\"><p>%@</p></span></body>",
                      genreID];
    return html;
}

@end
